baseURL = "https://www.kineto.ai"
languageCode = "en-us"
title = "KINETO"
theme = "beautifulhugo"

[params]
  subtitle = "Upskilling Professionals in Artificial Intelligence"
  logo = "/img/KI_avatar_white.png"
  favicon = "/img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = false
  gcse = ""
  
  # Cookie consent
  cookieConsent = true
  cookieConsentText = "This website uses cookies to provide you with the best possible user experience. By continuing to use this website, you consent to the use of cookies."
  cookieConsentButton = "Accept"

  # Homepage carousel images
  bigimg = [{src = "/img/triangle.jpg"}, {src = "/img/sphere.jpg"}, {src = "/img/hexagon.jpg"}]


[params.author]
  name = "Antonio Rueda-Toicen"
  website = "https://kineto.ai"
  email = "contact@kineto.ai"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Courses"
  url = "/courses/"
  weight = 2

  [[menu.main]]
    name = "Deep Learning"
    url = "/courses/deep-learning/"
    weight = 21
    parent = "Courses"

  [[menu.main]]
    name = "Diffusion Models"
    url = "/courses/diffusion-models/"
    weight = 22
    parent = "Courses"

  [[menu.main]]
    name = "Multimodal Agents"
    url = "/courses/multimodal-agents/"
    weight = 23
    parent = "Courses"

  [[menu.main]]
    name = "Practical Computer Vision Bootcamp"
    url = "/courses/practical-computer-vision-bootcamp/"
    weight = 24
    parent = "Courses"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5


[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    weight = 2
    title = "Kineto.ai - KI-Beratung"
    [languages.de.params]
      subtitle = "Unternehmen mit Künstlicher Intelligenz transformieren"

# German Menu
[[languages.de.menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[languages.de.menu.main]]
  name = "Kurse"
  url = "/courses/"
  weight = 2

  [[languages.de.menu.main]]
    name = "Deep Learning"
    url = "/courses/deep-learning/"
    weight = 21
    parent = "Kurse"

  [[languages.de.menu.main]]
    name = "Diffusion Models"
    url = "/courses/diffusion-models/"
    weight = 22
    parent = "Kurse"

  [[languages.de.menu.main]]
    name = "Multimodal Agents"
    url = "/courses/multimodal-agents/"
    weight = 23
    parent = "Kurse"

  [[languages.de.menu.main]]
    name = "Practical Computer Vision Bootcamp"
    url = "/courses/practical-computer-vision-bootcamp/"
    weight = 24
    parent = "Kurse"

[[languages.de.menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[[languages.de.menu.main]]
  name = "Über uns"
  url = "/about/"
  weight = 4

[[languages.de.menu.main]]
  name = "Kontakt"
  url = "/contact/"
  weight = 5